### ISSUE TITLE
IPv6 broken on the debgen.xyz website

### ISSUE THREAD

**Issue by romanrm** [rwarasaurus/debgen#2]
$ ping6 debgen.xyz
PING debgen.xyz(2a01:7e00::f03c:91ff:fe91:2a26 (2a01:7e00::f03c:91ff:fe91:2a26)) 56 data bytes
^C
--- debgen.xyz ping statistics ---
5 packets transmitted, 0 received, 100% packet loss, time 4100ms

 Host                               Loss%   Snt   Last   Avg  Best  Wrst StDev
 1. 2a02:2698:8000::505              0.0%    10    0.7   0.8   0.5   0.9   0.0
 2. 2a02:2698:8000::1e02             0.0%    10    0.8   2.7   0.6  19.0   5.7
 3. GW-ERTelecom.retn.net            0.0%    10   30.0  30.1  29.8  30.7   0.0
 4. ae10-153.RT.M9P.MSK.RU.retn.net  0.0%    10   30.0  30.2  29.8  31.2   0.0
 5. RT.TC2.LON.UK.retn.net           0.0%    10   74.1  73.9  73.7  74.2   0.0
 6. 2001:7f8:4::f9cd:1               0.0%    10   75.0  74.7  74.4  75.1   0.0
 7. ???

$ curl -v6 debgen.xyz
* Rebuilt URL to: debgen.xyz/
*   Trying 2a01:7e00::f03c:91ff:fe91:2a26...
* TCP_NODELAY set
* connect to 2a01:7e00::f03c:91ff:fe91:2a26 port 80 failed: Connection timed out
* Failed to connect to debgen.xyz port 80: Connection timed out
* Closing connection 0
curl: (7) Failed to connect to debgen.xyz port 80: Connection timed out

**Comment by rwarasaurus** [comment]
Ah its been disabled via
```
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
```
DNS lookups were very slow and the work around was to disable ipv6.

Is there a better way?

**Comment by romanrm** [comment]
Disabling IPV6 should not be the first resort to solve any network problem, there should be another way, such as using a different DNS service; 

But that's beside the point;

Main thing is that if you disable IPv6 on the web server, don't forget to also remove the AAAA record from DNS, else this will cause issues for visitors e.g. on NAT64/DNS64.

At the time this was bug report was posted, your domain used to have an AAAA of "2a01:7e00::f03c:91ff:fe91:2a26". It doesn't have that anymore, so you removed it since then. Thanks

**Comment by rwarasaurus** [comment]
I think with it being a really old vm ipv6 was still new and reading online it was suggested just to fix the dns resolution issues. I've had another look and it seem very straight forward now so I've updated the site and according to https://ipv6-test.com/ its working, could you verify that?

Thanks!

**Comment by romanrm** [comment]
Yes, it appears to work now. Thanks!

**Comment by theel0ja** [comment]
The site is broken on [NAT64](https://en.wikipedia.org/wiki/NAT64) clients, please delete the AAAA record or fix your IPv6.

**Comment by romanrm** [comment]
Oh yeah, it's broken again now, but in a different way than before:

$ curl -v6 debgen.xyz
* Rebuilt URL to: debgen.xyz/
*   Trying 2a01:7e00::f03c:92ff:fe37:154d...
* TCP_NODELAY set
* connect to 2a01:7e00::f03c:92ff:fe37:154d port 80 failed: Connection refused
* Failed to connect to debgen.xyz port 80: Connection refused
* Closing connection 0
curl: (7) Failed to connect to debgen.xyz port 80: Connection refused

Indeed, this time NAT64 users will not be able to visit.

**Comment by rwarasaurus** [comment]
IPv6 was fixed on the vm but not nginx! 

I've updated the config and looks like its working again.

```
curl -v6 -I https://debgen.xyz
* Rebuilt URL to: https://debgen.xyz/
*   Trying 2606:4700:3032::681b:8f99...
* TCP_NODELAY set
* Connected to debgen.xyz (2606:4700:3032::681b:8f99) port 443 (#0)
...
```

**Comment by theel0ja** [comment]
Looks like you switched to Cloudflare. However, the `2a01:7e00::f03c:92ff:fe37:154d` seems to respond now as well.
